server:
  port: 8080
  servlet:
    context-path: /mythaistar

logging:
  level:
    org.hibernate.SQL: debug
    
security:
  expose:
    error:
      details: false
      
spring:
  flyway:
    enabled: true
    clean-on-validation-error: true
    locations: classpath:db/migration,classpath:db/specific/h2
  profiles:
    active: h2mem
  mail:
    enabled: false
    host: smtp.gmail.com
    username: mythaistarrestaurant@gmail.com
    password: mythaistarrestaurant2501
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
        ddl-auto: validate
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
mythaistar:
  hourslimitcancellation: 1
  
client:
  port: 4200